[project]
name = "ere"
version = "0.1.0"
description = "A basic implementation of the Entity Resolution Engine (ERE)."
authors = [
    {name = "Marco Brandizi",email = "marco.brandizi@meaningfy.ws"}
]
readme = "README.md"
requires-python = "~=3.14.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# Needed when the root doesn't contain $project_name
packages = [
  { include = "*", from = "src" }
]


[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)",
    "assertpy (>=1.1,<2.0)",
    "rdflib (>=7.5.0,<8.0.0)",
    "brandizpyes (>=1.1.0,<2.0.0)",
    "ruff (>=0.9.0,<1.0.0)",
    "testcontainers[redis] (>=4.13.3,<5.0.0)",
]

[tool.poetry.dependencies]
pydantic = "^2.12.5"
redis = "^7.1.0"
linkml-runtime = "^1.9.5"
# TODO: should we have a registry?
# TODO: fix when merged to develop or release
ers-core = { git = "https://github.com/OP-TED/entity-resolution-spec.git", branch = "develop" }


[tool.pytest.ini_options]
addopts = [
  "-v", 
  "--basetemp=/tmp/pytest" # pytest-redis doesn't like long paths in macOS
]
# Skips warning from 3rd party libs, such as rdflib
filterwarnings = [
  "once",
  "ignore",
  "default::Warning:ere\\..*"
]
# Logging is set up in conftest.py


[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
